### Programming Lecture
##### 2ECE-C 
##### 08/27/24


#### Numphy

- core library for scientific and computing in python.
- High-performance multidimensional array object
- Tools for working with array.


- To access NumPy library, the import convention must be used.

ndarrays
- multidimensional container of items of the same type and size
- 1D array (3,)
- 2D array (2,3)
- 3D array (2,2,3)

# 1st Demo

In [13]:
#1D Array - vector

import numpy as np

el = np.array([1,2,3])

el 



array([1, 2, 3])

In [19]:
#2D Array - matrix


import numpy as np

psy = np.array ([(2.4,-1.5,1.1), (2.3, -2.5, -5.6)])

psy

array([[ 2.4, -1.5,  1.1],
       [ 2.3, -2.5, -5.6]])

In [21]:
#3D Array - tensor


import numpy as np 

kongroo = np.array([[(1.1, 2, 3.4),(7, 2.5, 9)],[(1,2,3),(9,8,7)]])
kongroo

array([[[1.1, 2. , 3.4],
        [7. , 2.5, 9. ]],

       [[1. , 2. , 3. ],
        [9. , 8. , 7. ]]])

In [23]:
y = np.ones((2,3))
y

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
z = np.arange(3, 7, 0.5)
z

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [25]:
np.linspace(3, 7, 10)

array([3.        , 3.44444444, 3.88888889, 4.33333333, 4.77777778,
       5.22222222, 5.66666667, 6.11111111, 6.55555556, 7.        ])

In [26]:
np.full((5,3),2.4)

array([[2.4, 2.4, 2.4],
       [2.4, 2.4, 2.4],
       [2.4, 2.4, 2.4],
       [2.4, 2.4, 2.4],
       [2.4, 2.4, 2.4]])

In [27]:
#identity matrix: np.eye(m) 
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
import numpy as np 
np.random.random((2,3))

array([[0.24745988, 0.33622489, 0.60072593],
       [0.16472416, 0.04961799, 0.02946757]])

#viewing the contents on a numpy file

#syntax = np.load('filename.npy')

data = np.load('filename')


data.shape 

data.ndim (dimension)

data.size

# 2nd Demo

In [39]:
a = np.array([(2,4,6),(8,10,12)])
a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [41]:
b = np.array([(4,2),(16,25),(36,49)])
b

array([[ 4,  2],
       [16, 25],
       [36, 49]])

In [42]:
c = np.array ([2,3,5])
c

array([2, 3, 5])

In [49]:
#Element-wise

c-a

array([[ 0, -1, -1],
       [-6, -7, -7]])

In [44]:
a+c

array([[ 4,  7, 11],
       [10, 13, 17]])

In [45]:
a*c


array([[ 4, 12, 30],
       [16, 30, 60]])

In [46]:
c*a

array([[ 4, 12, 30],
       [16, 30, 60]])

In [47]:
a/c

array([[1.        , 1.33333333, 1.2       ],
       [4.        , 3.33333333, 2.4       ]])

In [50]:
a


array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [51]:
b

array([[ 4,  2],
       [16, 25],
       [36, 49]])

In [52]:
np.exp(b)

array([[5.45981500e+01, 7.38905610e+00],
       [8.88611052e+06, 7.20048993e+10],
       [4.31123155e+15, 1.90734657e+21]])

In [53]:
np.sqrt(b)

array([[2.        , 1.41421356],
       [4.        , 5.        ],
       [6.        , 7.        ]])

In [54]:
np.sin(b)

array([[-0.7568025 ,  0.90929743],
       [-0.28790332, -0.13235175],
       [-0.99177885, -0.95375265]])

In [55]:
np.log(b)

array([[1.38629436, 0.69314718],
       [2.77258872, 3.21887582],
       [3.58351894, 3.8918203 ]])

In [57]:
a = np.array([2,3,5])
a

array([2, 3, 5])

In [59]:
b = np.array([(1,2,5),(4,5,6),(7,8,9)])
b

array([[1, 2, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
# = is an assignment operator
c = a
c

array([2, 3, 5])

In [69]:
# = is an assignment operator
a == b

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [75]:
b < 7

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [77]:
a > 2

array([ True,  True,  True])

In [73]:
#as a group

np.array_equal(a,b)

False

In [74]:
np.array_equal(a,c)

True

# 3rd Demo

In [79]:
A = np.array([(1,2,3),(4,5,6),(7,8,9)])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Subsetting, Slicing, Indexing ndarrays

Subsetting- getting a certain element from the array or structure

In [80]:
A[1,1] #or A[1][1]


5

In [81]:
A[2,1]

8

Slicing- getting the portion from an array or structure

In [84]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
A[1:2]

array([[4, 5, 6]])

In [86]:
A[0:3,2]

array([3, 6, 9])

In [87]:
A[1]

array([4, 5, 6])

Indexing - getting a certain element or portion depending on the condition

In [91]:
A[A<7]

array([1, 2, 3, 4, 5, 6])

In [92]:
A[A>2]

array([3, 4, 5, 6, 7, 8, 9])

In [100]:
A[A==5]

array([5])

# 4th Demo - Array Manipulation

In [98]:
a = np.array([3,2,1])
a

array([3, 2, 1])

In [101]:
b = np.array([(4,5,6),(3,2,1)])
b

array([[4, 5, 6],
       [3, 2, 1]])

In [103]:
c = np.linspace (10,20,3)
c

array([10., 15., 20.])

In [104]:
d = np.full((2,2),7)
d

array([[7, 7],
       [7, 7]])

In [106]:
e = np.eye(2)
e

array([[1., 0.],
       [0., 1.]])

In [109]:
a.sort()
a

array([1, 2, 3])

In [111]:
b.sort(axis=0) #pag axis 0 row
b

array([[3, 2, 1],
       [4, 5, 6]])

In [112]:
b.sort(axis=1) #pag axis 1 column}
b

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
np.shape(b)

(2, 3)

In [136]:
b.reshape(6,1).reshape
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [135]:
b.resize(6,1)
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [125]:
d

array([[7, 7],
       [7, 7]])

In [126]:
e

array([[1., 0.],
       [0., 1.]])

In [137]:
np.append(d,e)

array([7., 7., 7., 7., 1., 0., 0., 1.])

In [138]:
a

array([1, 2, 3])

In [139]:
np.insert(a,1,5)

array([1, 5, 2, 3])

In [140]:
np.delete(a,[2])

array([1, 2])

In [141]:
np.concatenate((a,c),axis=0)

array([ 1.,  2.,  3., 10., 15., 20.])

In [142]:
np.vstack((a,c))

array([[ 1.,  2.,  3.],
       [10., 15., 20.]])

In [143]:
np.hstack((d,e))

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [144]:
np.hsplit(a,3)

[array([1]), array([2]), array([3])]

In [147]:
np.vsplit(e,2)

[array([[1., 0.]]), array([[0., 1.]])]